### ISSUE TITLE
最新的更新（Commits on Apr 18, 2019）的hotpath经常使风扇满速转动

### ISSUE THREAD

**Issue by resunne** [YGQ8988/dell-3568#1]
最新的更新的hotpath使风扇风扇经常满速转动，噪声比较大，请问这个是哪个SSDT导致的呢？

**Comment by resunne** [comment]
> 最新的更新的hotpath使风扇风扇经常满速转动，噪声比较大，请问这个是哪个SSDT导致的呢？

找到原因了，使DDGPU.aml的原因，我换回了旧版的

**Comment by YGQ8988** [comment]
> > 最新的更新的hotpath使风扇风扇经常满速转动，噪声比较大，请问这个是哪个SSDT导致的呢？
> 
> 找到原因了，使DDGPU.aml的原因，我换回了旧版的

我自己机器没有这问题，如替换过程中出现问题，建议清除EFI目录下所有.开头的文件和文件夹，再重试看效果。
